// <auto-generated />
using System;
using Maurice.Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Maurice.Data.Migrations
{
    [DbContext(typeof(MauriceDbContext))]
    [Migration("20251029030633_usoCFDI")]
    partial class usoCFDI
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.9");

            modelBuilder.Entity("Maurice.Data.Models.Factura", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Base")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaveProdServ")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("TEXT");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Folio")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("ImporteImpuesto")
                        .HasColumnType("TEXT");

                    b.Property<string>("NombreEmisor")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ProcessedDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("RegimenFiscalReceptor")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("RetencionImpuesto")
                        .HasColumnType("TEXT");

                    b.Property<string>("RfcEmisor")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("TEXT");

                    b.Property<string>("RfcReceptor")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("SubTotal")
                        .HasColumnType("TEXT");

                    b.Property<string>("Tasa")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TipoDeDocumento")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("TipoDeTransaccion")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Total")
                        .HasColumnType("TEXT");

                    b.Property<string>("UUID")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("UsoCFDI")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UUID")
                        .IsUnique();

                    b.ToTable("Facturas");
                });

            modelBuilder.Entity("Maurice.Data.Models.Nomina", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("TEXT");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Folio")
                        .HasColumnType("TEXT");

                    b.Property<string>("NombreEmisor")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ProcessedDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("RegimenFiscalReceptor")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RfcEmisor")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("TEXT");

                    b.Property<string>("RfcReceptor")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("SubTotal")
                        .HasColumnType("TEXT");

                    b.Property<string>("TipoDeDocumento")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("TipoDeTransaccion")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Total")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TotalDeducciones")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TotalExento")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TotalGravado")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TotalImpuestosRetenidos")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TotalOtrasDeducciones")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TotalPercepciones")
                        .HasColumnType("TEXT");

                    b.Property<string>("UUID")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("UsoCFDI")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UUID")
                        .IsUnique();

                    b.ToTable("Nominas");
                });

            modelBuilder.Entity("Maurice.Data.Models.RegimenFiscal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Clave")
                        .HasMaxLength(3)
                        .HasColumnType("INTEGER");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("RegimenesFiscales");
                });

            modelBuilder.Entity("Maurice.Data.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Rfc")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Maurice.Data.Models.UsoCFDI", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Clave")
                        .IsRequired()
                        .HasMaxLength(4)
                        .HasColumnType("TEXT");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("UsosCFDI");
                });

            modelBuilder.Entity("Maurice.Data.Models.RegimenFiscal", b =>
                {
                    b.HasOne("Maurice.Data.Models.User", null)
                        .WithMany("RegimenesFiscales")
                        .HasForeignKey("UserId");
                });

            modelBuilder.Entity("Maurice.Data.Models.User", b =>
                {
                    b.Navigation("RegimenesFiscales");
                });
#pragma warning restore 612, 618
        }
    }
}
